import os
import sys
from multiprocessing import Queue
from .. import MAX_QUEUE_SIZE

sys.path.append(os.path.dirname(os.path.realpath(__file__)))

""" =============== GENERAL UTILITY CLASSES AND FUNCTIONS =============== """


# SECURE GLOBAL REQUESTS
SECURE_GLOBAL_REQUEST_QUEUE = Queue(MAX_QUEUE_SIZE)
SECURE_GET_NEXT_REQUEST = SECURE_GLOBAL_REQUEST_QUEUE.get_nowait
SECURE_MAKE_REQUEST = SECURE_GLOBAL_REQUEST_QUEUE.put_nowait

# SECURE GLOBAL RESPONSES
SECURE_GLOBAL_RESPONSE_QUEUE = Queue(MAX_QUEUE_SIZE)
SECURE_GET_NEXT_RESPONSE = SECURE_GLOBAL_RESPONSE_QUEUE.get_nowait
SECURE_SEND_RESPONSE = SECURE_GLOBAL_RESPONSE_QUEUE.put_nowait

# INSECURE GLOBAL REQUESTS
INSECURE_GLOBAL_REQUEST_QUEUE = Queue(MAX_QUEUE_SIZE)
INSECURE_GET_NEXT_REQUEST = INSECURE_GLOBAL_REQUEST_QUEUE.get_nowait
INSECURE_MAKE_REQUEST = INSECURE_GLOBAL_REQUEST_QUEUE.put_nowait

# INSECURE GLOBAL RESPONSES
INSECURE_GLOBAL_RESPONSE_QUEUE = Queue(MAX_QUEUE_SIZE)
INSECURE_GET_NEXT_RESPONSE = INSECURE_GLOBAL_RESPONSE_QUEUE.get_nowait
INSECURE_SEND_RESPONSE = INSECURE_GLOBAL_RESPONSE_QUEUE.put_nowait
